//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VA_Analysemodul.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VA_Analysemodul.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legg til relasjon.
        /// </summary>
        internal static string AddRelation {
            get {
                return ResourceManager.GetString("AddRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And / Or.
        /// </summary>
        internal static string AndOr {
            get {
                return ResourceManager.GetString("AndOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angi dokument....
        /// </summary>
        internal static string BrowseDocument {
            get {
                return ResourceManager.GetString("BrowseDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brukernavn.
        /// </summary>
        internal static string Brukernavn {
            get {
                return ResourceManager.GetString("Brukernavn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bufferstørrelse.
        /// </summary>
        internal static string BufferDistance {
            get {
                return ResourceManager.GetString("BufferDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endre bruker.
        /// </summary>
        internal static string ChangeUser {
            get {
                return ResourceManager.GetString("ChangeUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tøm felter.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lagre ny modell.
        /// </summary>
        internal static string CreateNewModel {
            get {
                return ResourceManager.GetString("CreateNewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datakilde.
        /// </summary>
        internal static string DataSource {
            get {
                return ResourceManager.GetString("DataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dato endret.
        /// </summary>
        internal static string DateChanged {
            get {
                return ResourceManager.GetString("DateChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dato opprettet - endret.
        /// </summary>
        internal static string DateCreaCh {
            get {
                return ResourceManager.GetString("DateCreaCh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dato opprettet.
        /// </summary>
        internal static string DateCreated {
            get {
                return ResourceManager.GetString("DateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Først kjørt.
        /// </summary>
        internal static string DateFirst {
            get {
                return ResourceManager.GetString("DateFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dato først - sist kjørt.
        /// </summary>
        internal static string DateFirstLast {
            get {
                return ResourceManager.GetString("DateFirstLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sist kjørt.
        /// </summary>
        internal static string DateLast {
            get {
                return ResourceManager.GetString("DateLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slett feltspørring.
        /// </summary>
        internal static string DeleteFieldQuery {
            get {
                return ResourceManager.GetString("DeleteFieldQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slett modell.
        /// </summary>
        internal static string DeleteModel {
            get {
                return ResourceManager.GetString("DeleteModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slett relasjon.
        /// </summary>
        internal static string DeleteRelation {
            get {
                return ResourceManager.GetString("DeleteRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kobling relasjosnfelt.
        /// </summary>
        internal static string DestTabRelField {
            get {
                return ResourceManager.GetString("DestTabRelField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rediger informasjon.
        /// </summary>
        internal static string EditDesc {
            get {
                return ResourceManager.GetString("EditDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endre spørring.
        /// </summary>
        internal static string EditQuery {
            get {
                return ResourceManager.GetString("EditQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feltnavn.
        /// </summary>
        internal static string Fieldname {
            get {
                return ResourceManager.GetString("Fieldname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feltverdi.
        /// </summary>
        internal static string FieldValue {
            get {
                return ResourceManager.GetString("FieldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feltverdiliste.
        /// </summary>
        internal static string FieldValueList {
            get {
                return ResourceManager.GetString("FieldValueList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta med objekter uten relaterte rader.
        /// </summary>
        internal static string IncludeFeatures {
            get {
                return ResourceManager.GetString("IncludeFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopier modell.
        /// </summary>
        internal static string KopierModell {
            get {
                return ResourceManager.GetString("KopierModell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lagnavn.
        /// </summary>
        internal static string LayerName {
            get {
                return ResourceManager.GetString("LayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logg inn.
        /// </summary>
        internal static string LoggIn {
            get {
                return ResourceManager.GetString("LoggIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modell.
        /// </summary>
        internal static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modell beskrivelse.
        /// </summary>
        internal static string ModelDesc {
            get {
                return ResourceManager.GetString("ModelDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modell id.
        /// </summary>
        internal static string ModelId {
            get {
                return ResourceManager.GetString("ModelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modellnavn.
        /// </summary>
        internal static string ModelName {
            get {
                return ResourceManager.GetString("ModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eier.
        /// </summary>
        internal static string ModelOwner {
            get {
                return ResourceManager.GetString("ModelOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datakilde.
        /// </summary>
        internal static string ModelSource {
            get {
                return ResourceManager.GetString("ModelSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lagre feltspørring.
        /// </summary>
        internal static string NewFieldQuery {
            get {
                return ResourceManager.GetString("NewFieldQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objektklasse.
        /// </summary>
        internal static string Objectclass {
            get {
                return ResourceManager.GetString("Objectclass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objektklasse.
        /// </summary>
        internal static string ObjectClassTable {
            get {
                return ResourceManager.GetString("ObjectClassTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Åpne informasjon.
        /// </summary>
        internal static string OpenDoc {
            get {
                return ResourceManager.GetString("OpenDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Åpne dokument.
        /// </summary>
        internal static string OpenDocument {
            get {
                return ResourceManager.GetString("OpenDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operatør.
        /// </summary>
        internal static string Operator {
            get {
                return ResourceManager.GetString("Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternativer.
        /// </summary>
        internal static string Option {
            get {
                return ResourceManager.GetString("Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opprinnelig relasjonsfelt.
        /// </summary>
        internal static string OriginTabRelField {
            get {
                return ResourceManager.GetString("OriginTabRelField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ).
        /// </summary>
        internal static string PEnd {
            get {
                return ResourceManager.GetString("PEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (.
        /// </summary>
        internal static string PStart {
            get {
                return ResourceManager.GetString("PStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relasjonstype.
        /// </summary>
        internal static string RelationType {
            get {
                return ResourceManager.GetString("RelationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kjør modell.
        /// </summary>
        internal static string RunModel {
            get {
                return ResourceManager.GetString("RunModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lagre endringer.
        /// </summary>
        internal static string SaveEdits {
            get {
                return ResourceManager.GetString("SaveEdits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lagre relasjon.
        /// </summary>
        internal static string SaveRelation {
            get {
                return ResourceManager.GetString("SaveRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lagre metode.
        /// </summary>
        internal static string SaveSelectionMode {
            get {
                return ResourceManager.GetString("SaveSelectionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Søk.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleksjonsmetode for OR-feltet til relaterte tabeller.
        /// </summary>
        internal static string SelectionMode {
            get {
                return ResourceManager.GetString("SelectionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleksjonstype.
        /// </summary>
        internal static string SelectionType {
            get {
                return ResourceManager.GetString("SelectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorter.
        /// </summary>
        internal static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romlig relasjonstype.
        /// </summary>
        internal static string SpatialRelType {
            get {
                return ResourceManager.GetString("SpatialRelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opprett eller rediger modell.
        /// </summary>
        internal static string TitleDesignDialog {
            get {
                return ResourceManager.GetString("TitleDesignDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opprett eller rediger spørring.
        /// </summary>
        internal static string TitleEditQuery {
            get {
                return ResourceManager.GetString("TitleEditQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logg inn.
        /// </summary>
        internal static string TitleLoggInn {
            get {
                return ResourceManager.GetString("TitleLoggInn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modellbeskrivelse og dokumentasjon.
        /// </summary>
        internal static string TitleModelInfo {
            get {
                return ResourceManager.GetString("TitleModelInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Innstillinger for modellkjøring.
        /// </summary>
        internal static string TitleOption {
            get {
                return ResourceManager.GetString("TitleOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unik.
        /// </summary>
        internal static string Unique {
            get {
                return ResourceManager.GetString("Unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brukernavn.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
    }
}
